### PR TITLE
use different form of dokku sync

### PR DESCRIPTION
**Pull request by lizthegrey**
`dokku git:sync --build roster-staging https://github.com/eve-val/eve-roster.git master` will run automatically, as COMMAND is overridden.

### CODE REVIEW

**Comment by ayust** [comment]
Does this mean that *anyone* successfully SSHing to `dokku@of-sound-mind.com` will be forced to run this instead of getting a shell? Or is this something CircleCI specifically overrides?

**Comment by lizthegrey** [comment]
> Does this mean that _anyone_ successfully SSHing to `dokku@of-sound-mind.com` will be forced to run this instead of getting a shell? Or is this something CircleCI specifically overrides?

Correct, someone successfully sshing to dokku@of-sound-mind.com with that SSH key will be forced to run this.

**Comment by ayust** [comment]
Does yaml have a comment syntax? If so, could we explain that in this config? Otherwise it looks kind of magic.

**Comment by lizthegrey** [comment]
> Does yaml have a comment syntax? If so, could we explain that in this config? Otherwise it looks kind of magic.

changed name of the circle step!

**Pull request merged**
